//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SeeYouSite.Models
{
    public partial class conquistas
    {
        public conquistas()
        {
            this.usuarios_conquistas = new HashSet<usuarios_conquistas>();
        }
    
        public long id_conquista { get; set; }
        public Nullable<System.DateTime> data_conquista { get; set; }
        public string descricao { get; set; }
        public string conquista { get; set; }
    
        public virtual ICollection<usuarios_conquistas> usuarios_conquistas { get; set; }
    }
    
}
