//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SeeYouSite.Models
{
    public partial class funcoes_usuarios
    {
        public long id_funcoes_usuarios { get; set; }
        public Nullable<long> id_usuario { get; set; }
        public Nullable<int> id_funcao { get; set; }
    
        public virtual funcoes funcoes { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
    
}
