//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SeeYouSite.Models
{
    public partial class permissoes
    {
        public long id_permissao { get; set; }
        public string escrita { get; set; }
        public string leitura_escrita { get; set; }
        public string leitura { get; set; }
    }
    
}
