//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SeeYouSite.Models
{
    public partial class grupos
    {
        public grupos()
        {
            this.usuarios_grupos = new HashSet<usuarios_grupos>();
        }
    
        public long id_grupo { get; set; }
        public string descricao { get; set; }
        public Nullable<System.DateTime> data_criacao { get; set; }
        public string grupo { get; set; }
    
        public virtual ICollection<usuarios_grupos> usuarios_grupos { get; set; }
    }
    
}
