//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace SeeYouSite.Models
{
    public partial class SYRContext : DbContext
    {
        public SYRContext()
            : base("name=SYRContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<comentarios> comentarios { get; set; }
        public DbSet<conquistas> conquistas { get; set; }
        public DbSet<funcoes> funcoes { get; set; }
        public DbSet<funcoes_usuarios> funcoes_usuarios { get; set; }
        public DbSet<grupos> grupos { get; set; }
        public DbSet<imagens> imagens { get; set; }
        public DbSet<permissoes> permissoes { get; set; }
        public DbSet<usuarios> usuarios { get; set; }
        public DbSet<usuarios_conquistas> usuarios_conquistas { get; set; }
        public DbSet<usuarios_grupos> usuarios_grupos { get; set; }
        public DbSet<percursos> percursos { get; set; }
        public DbSet<pontos> pontos { get; set; }
    }
}
