//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SeeYouSite.Models
{
    public partial class percursos
    {
        public percursos()
        {
            this.comentarios = new HashSet<comentarios>();
            this.pontos = new HashSet<pontos>();
        }
    
        public long id_percurso { get; set; }
        public Nullable<long> id_usuario { get; set; }
        public Nullable<System.DateTime> data_percurso { get; set; }
        public string percurso { get; set; }
        public string descricao { get; set; }
        public string compartilhado { get; set; }
        public Nullable<double> caloria { get; set; }
        public Nullable<double> distancia { get; set; }
        public Nullable<double> altitude_min { get; set; }
        public Nullable<double> altitude_med { get; set; }
        public Nullable<double> altitude_max { get; set; }
        public Nullable<double> Pace { get; set; }
        public Nullable<double> velocidade_med { get; set; }
        public Nullable<double> velocidade_max { get; set; }
        public byte[] imagem { get; set; }
        public string duracao { get; set; }
        public string isMetrico { get; set; }
    
        public virtual ICollection<comentarios> comentarios { get; set; }
        public virtual usuarios usuarios { get; set; }
        public virtual ICollection<pontos> pontos { get; set; }
    }
    
}
